### ISSUE TITLE
Feature request: Optionally set a `timeout` value for requests

### ISSUE THREAD

**Issue by albertferras-verse** [alice-biometrics/onboarding-python#56]
None of the `requests.get/post/delete` calls to Alice API includes a `timeout` parameter. When the `timeout` value is not specified, then no timeout will happen and the call will wait forever.
Could you add a way to configure the `timeout` value so that we can control how much time we want to wait for the response?

**Why we need this**
This is causing issues for us because if Alice is down then our requests get stuck and our workers end up dying.

**Comment by fgsalomon** [comment]
Available in [v1.11.0](https://github.com/alice-biometrics/onboarding-python/releases/tag/v1.11.0)
